apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-docker-kubernetes-deployment
  labels:
    app: sample-docker-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-docker-kubernetes
  template:
    metadata:
      labels:
        app: sample-docker-kubernetes
    spec:
      containers:
      - name: sample-docker-kubernetes
        image: khushi1701/sample-docker-kubernetes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-docker-kubernetes-service
spec:
  type: NodePort
  selector:
    app: sample-docker-kubernetes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080