# Use root/example as user/password credentials
version: '3.1'

services:
  application:
    image: khushi1701/spring-mongo-docker-kubernetes
    ports:
      - 3003:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: mongoadmin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
volumes:
  mongo-data:
    driver: local